In [1]:
import json
from shapely.geometry import Point, Polygon, MultiPolygon
import geojson
import geopandas as gpd
import pandas as pd
import numpy as np
from time import time
import leafmap.foliumap as leafmap
import supervision as sv
from garuda.od import ConfusionMatrix
from IPython.display import Markdown

In [2]:
region = 'Islamabad'
prediction_file = f"../data/predict/processed_labels/{region}/predictions_0.25.geojson"
print(f"Region: {region}")
print(f"Prediction file: {prediction_file}")

Region: Islamabad
Prediction file: ../data/predict/processed_labels/Islamabad/predictions_0.25.geojson

In [3]:
prediction_gdf = gpd.read_file(prediction_file) 
prediction_gdf['yolo_label'] = prediction_gdf['yolo_label'].apply(lambda x: np.array(list(map(float, x.split("_")))))
print(len(prediction_gdf))
print(prediction_gdf.crs)
prediction_gdf.head()

6
EPSG:3857

,x,y,class_name,confidence,yolo_label,geometry
0,8121895,3982366,CFCBK,0.260871,"[0.0, 0.719664, 0.637984, 0.746819, 0.640509, ...","POLYGON ((8122566.884 3981944.901, 8122649.909..."
1,8113640,3979615,FCBK,0.894629,"[1.0, 0.24885, 0.871705, 0.264374, 0.879914, 0...","POLYGON ((8112872.18 3978478.57, 8112919.644 3..."
2,8113640,3979615,FCBK,0.693731,"[1.0, 0.292658, 0.840746, 0.310782, 0.844156, ...","POLYGON ((8113006.122 3978573.227, 8113061.535..."
3,8113640,3979615,Zigzag,0.303295,"[2.0, 0.86641, 0.71868, 0.885333, 0.713032, 0....","POLYGON ((8114760.358 3978946.441, 8114818.214..."
4,8116391,3979615,FCBK,0.904258,"[1.0, 0.393959, 0.155327, 0.409872, 0.160645, ...","POLYGON ((8116067.581 3980668.883, 8116116.234..."

In [4]:
prediction_gdf.crs.to_string()
print(prediction_gdf.tail(2))

         x        y class_name  confidence  \
4  8116391  3979615       FCBK    0.904258
5  8116391  3979615       FCBK    0.543410

                                          yolo_label  \
4  [1.0, 0.393959, 0.155327, 0.409872, 0.160645, ...
5  [1.0, 0.0684259, 0.736806, 0.068567, 0.716824,...

                                            geometry
4  POLYGON ((8116067.581 3980668.883, 8116116.234...
5  POLYGON ((8115072.269 3978891.022, 8115072.701...

In [5]:
prediction_gdf.reset_index(inplace=True, drop=True)
print(prediction_gdf.head(2))

         x        y class_name  confidence  \
0  8121895  3982366      CFCBK    0.260871
1  8113640  3979615       FCBK    0.894629

                                          yolo_label  \
0  [0.0, 0.719664, 0.637984, 0.746819, 0.640509, ...
1  [1.0, 0.24885, 0.871705, 0.264374, 0.879914, 0...

                                            geometry
0  POLYGON ((8122566.884 3981944.901, 8122649.909...
1  POLYGON ((8112872.18 3978478.57, 8112919.644 3...

In [6]:
intersection_gdf = gpd.sjoin(prediction_gdf, prediction_gdf, predicate="intersects")[['index_right']].reset_index()
intersection_gdf = intersection_gdf[intersection_gdf['index'] < intersection_gdf['index_right']]
len(intersection_gdf)

0

In [7]:
def get_iou(row):
    left_polygon = prediction_gdf.iloc[int(row['index'])]['geometry']
    right_polygon = prediction_gdf.iloc[int(row['index_right'])]['geometry']
    left_area = left_polygon.area
    right_area = right_polygon.area
    iou = left_polygon.intersection(right_polygon).area / left_polygon.union(right_polygon).area
    return iou, left_area, right_area

intersection_gdf[['iou', 'left_area', 'right_area']] = intersection_gdf.apply(get_iou, axis=1, result_type="expand")
intersection_gdf = intersection_gdf[intersection_gdf['iou'] > 0.33]
len(intersection_gdf)
print(intersection_gdf.head(2))

ValueError: Columns must be same length as key

In [ ]:
drop_idx = intersection_gdf.apply(lambda x: x['index'] if x['left_area'] < x['right_area'] else x['index_right'], axis=1).astype(int).values
print(len(prediction_gdf))
prediction_gdf.drop(drop_idx, inplace=True)
print(len(prediction_gdf))
display(prediction_gdf.head(2))

202
200

,x,y,class_name,confidence,yolo_label,geometry
0,10225442,2784751,Zigzag,0.782646,"[2.0, 0.354836, 0.999618, 0.368349, 0.99992, 0...","POLYGON ((10224998.447 2783223.853, 10225039.7..."
1,10222690,2793006,Zigzag,0.832081,"[2.0, 0.679098, 0.238839, 0.692999, 0.241333, ...","POLYGON ((10223238.139 2793805.119, 10223280.6..."

In [ ]:
final_kilns=prediction_gdf.to_crs(epsg=4326)
display(final_kilns.head(2))

,x,y,class_name,confidence,yolo_label,geometry
0,10225442,2784751,Zigzag,0.782646,"[2.0, 0.354836, 0.999618, 0.368349, 0.99992, 0...","POLYGON ((91.85272 24.24445, 91.85309 24.24444..."
1,10222690,2793006,Zigzag,0.832081,"[2.0, 0.679098, 0.238839, 0.692999, 0.241333, ...","POLYGON ((91.83691 24.33109, 91.83729 24.33103..."

In [ ]:
import os
save_handvalidation_dir = f"../hand_validation_jeet/{region}"
os.makedirs(save_handvalidation_dir, exist_ok=True)

In [ ]:
len(final_kilns)

200

In [ ]:
version = "v3"  
batch_size = 500
for i in range(0, len(final_kilns), batch_size):
    end = min(i+batch_size, len(final_kilns))
    final_kilns.iloc[i:i+batch_size].to_file(f"../hand_validation/{region}/{version}_potential_kiln_{region}_{i}_{end-1}.geojson", driver='GeoJSON')

GARUDA INFO     : Created 200 records